---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-ktunnel
  labels:
    app: opendatahub-operator-controller
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opendatahub-operator-controller
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: ktunnel
      labels:
        app: opendatahub-operator-controller
        control-plane: controller-manager
    spec:
      containers:
        - name: ktunnel
          image: quay.io/omrikiei/ktunnel:v1.5.3
          imagePullPolicy: IfNotPresent
          command:
            - /ktunnel/ktunnel
          args:
            - server
            - -p
            - "28688"
          ports:
            - containerPort: 9443
              name: webhook
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 256Mi
